# Generated by Django 2.2.7 on 2019-12-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('hospital', '0001_initial'),
        ('account', '0002_auto_20191211_1537'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='r_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='p_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='p_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='p_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='h_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account'),
        ),
    ]
